Repository osmlab/name-suggestion-index, pull requests merged in 2018-10, with the labels that each got.

#2118 Fixed #1784 and added data for few chains stores.
  config/canonical.json
Labels: bulk

#2130 Removed pseudo-generic Vision Plus entry
  config/canonical.json
  config/filters.json
  dist/discardNames.json
  dist/keepNames.json
Labels: question

#2110 tiger mart (ExxonMobil)
  config/canonical.json
Labels: needs wikidata

#2136 Fix duplication of Western Union and add brand:wikidata, brand:wikipedia
  config/canonical.json
Labels: question

#2144 Halfords
  config/canonical.json
Labels: question

#2160 add wikidata/wikipedia for 8 banks
  config/canonical.json
Labels: bulk
