Repository osmlab/name-suggestion-index, pull requests merged in 2019-06, with the labels that each got.

#2739 Paris Baguette
  brands/shop/bakery.json
Labels: check local

#2628 Add UK outdoor shops Millets and Blacks
  brands/shop/outdoor.json
Labels: needs wikidata

#2783 Major credit unions of Canada
  brands/amenity/bank.json
Labels: bulk

#2784 Major U.S. credit unions
  brands/amenity/bank.json
Labels: bulk

#2797 Major boba tea chains
  brands/amenity/cafe.json
Labels: bulk
