Repository osmlab/name-suggestion-index, pull requests merged in 2022-11, with the labels that each got.

#7301 Add Wikidata Search Link
  app/src/CategoryRow.jsx
  docs/index.js
  docs/index.js.map
Labels: enhancement, nsi.guide

#7429 Add Chopstix
  data/brands/amenity/fast_food.json
Labels: needs wikidata

#7462 Fix Overpass quotation marks issue.
  app/src/CategoryRow.jsx
  docs/index.js
  docs/index.js.map
Labels: bug, nsi.guide
