Repository osmlab/name-suggestion-index, pull requests merged in 2022-01, with the labels that each got.

#5930 Add UK Salvation Army Recycling Boxes
  data/brands/amenity/recycling.json
Labels: needs research

#6029 Add Wienerroither bakery chain
  data/brands/shop/bakery.json
Labels: good first issue, needs wikidata

#6020 Parcel locker category change
  config/matchGroups.json
  data/brands/amenity/parcel_locker.json
  data/brands/amenity/vending_machine.json
Labels: waitfor

#6092 London Farmers' Market
  data/operators/amenity/marketplace.json
Labels: new category

#6106 RingGo parking ticket machines
  data/operators/amenity/vending_machine.json
Labels: new category
