Repository osmlab/name-suggestion-index, pull requests merged in 2022-10, with the labels that each got.

#7218 Fix apollostation, Shell in Japan
  data/brands/amenity/fuel.json
Labels: multiple companies

#7265 Create model.json and Add TamTam(タムタム), Popondetta(ポポンデッタ)
  data/brands/shop/model.json
Labels: new category

#7226 Tidy locationSet during build
  scripts/build_index.js
Labels: enhancement

#7288 Display preserveTags on nsi.guide
  app/src/Category.jsx
  app/src/CategoryRow.jsx
  docs/index.js
  docs/index.js.map
Labels: enhancement, nsi.guide

#5734 Add local Goodwill affiliates as operators
  config/matchGroups.json
  data/brands/shop/charity.json
  data/brands/shop/clothes.json
  data/operators/amenity/bicycle_parking.json
  data/operators/amenity/charging_station.json
  data/operators/amenity/clinic.json
  data/operators/amenity/drinking_water.json
  data/operators/amenity/hospital.json
  data/operators/amenity/parking.json
  data/operators/shop/charity.json
  data/operators/telecom/data_center.json
  data/operators/telecom/exchange.json
  lib/idgen.js
Labels: multiple companies, add brand
