Repository osmlab/name-suggestion-index, pull requests merged in 2023-03, with the labels that each got.

#7834 Escape the + symbol within the var Needle
  app/src/CategoryRow.jsx
  docs/index.js
  docs/index.js.map
Labels: bug, nsi.guide

#7395 Create tram_stop.json
  data/transit/railway/tram_stop.json
Labels: needs research, new category

#7934 Set location, add vending type for BWT Aqua
  data/brands/amenity/vending_machine.json
Labels: needs wikidata
