Repository osmlab/name-suggestion-index, pull requests merged in 2023-04, with the labels that each got.

#7976 Add VeAn Tattoo
  data/brands/shop/tattoo.json
Labels: considering, new category

#7949 Support Weibo as the social links
  app/src/CategoryRowSocialLinks.jsx
  scripts/build_wikidata.js
Labels: enhancement, nsi.guide, javascript

#7988 Support Weixin (Wechat) as the social links
  app/src/CategoryRowSocialLinks.jsx
  scripts/build_wikidata.js
Labels: enhancement, nsi.guide, javascript

#7945 Change operator key to network for OSP in Poland
  data/operators/amenity/fire_station.json
Labels: needs research, tagging
