Repository osmlab/name-suggestion-index, pull requests merged in 2025-08, with the labels that each got.

#11156 Make RBC Royal Bank local-language aware.
  data/brands/amenity/bank.json
Labels: tagging, needs discussion

#11227 Add Claudio
  data/brands/shop/supermarket.json
Labels: add brand

#11175 Add Church's Shoes
  data/brands/shop/shoes.json
Labels: add brand

#11176 Update branding for Moss
  data/brands/shop/clothes.json
Labels: tagging

#11173 add Return and Earn bottle return for AU-NSW
  data/brands/amenity/vending_machine.json
Labels: needs discussion
